// student-portal/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService, User } from '../../services/auth.service';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {
  user: User | null = null;

  constructor(private auth: AuthService) {}

  ngOnInit(): void {
    this.user = this.auth.getUser();
  }

  logout(): void {
    this.auth.logout().subscribe({
      complete: () => window.location.replace('/login'),
      error:    () => window.location.replace('/login')
    });
  }
}

<nav class="sidebar">
  <div class="p-3 border-bottom">
    <div class="fw-bold" style="font-size: 0.95rem; color: #111827;">Knowledge Hub</div>
    <div class="text-muted" style="font-size: 0.72rem;">Student Portal</div>
  </div>

  <div class="d-flex align-items-center gap-2 p-3 border-bottom bg-light" *ngIf="user">
    <div class="user-avatar">{{ user.name[0].toUpperCase() }}</div>
    <div class="overflow-hidden">
      <div class="fw-semibold text-truncate" style="font-size: 0.82rem; color: #111827;">{{ user.name }}</div>
      <div class="text-muted" style="font-size: 0.72rem;">{{ user.department }}</div>
    </div>
  </div>

  <ul class="nav flex-column flex-grow-1 py-2">
    <li class="nav-item">
      <a routerLink="/dashboard" routerLinkActive="active" class="nav-link">Dashboard</a>
    </li>
    <li class="nav-item">
      <a routerLink="/materials" routerLinkActive="active" class="nav-link">Study Materials</a>
    </li>
    <li class="nav-item">
      <a routerLink="/question-papers" routerLinkActive="active" class="nav-link">Question Papers</a>
    </li>
    <li class="nav-item">
      <a routerLink="/search" routerLinkActive="active" class="nav-link">Search</a>
    </li>
  </ul>

  <div class="p-3 border-top">
    <button class="btn btn-outline-danger btn-sm w-100" (click)="logout()">Logout</button>
  </div>
</nav>

// admin-portal/src/components/Sidebar.jsx
import { NavLink } from 'react-router-dom';
import api from '../api/axios';

function Sidebar() {
  const user = JSON.parse(localStorage.getItem('dkh_admin') || 'null');

  const handleLogout = async () => {
    try { await api.post('/logout'); } catch {}
    localStorage.removeItem('dkh_admin');
    // Use hard redirect so React fully resets — prevents stale auth state
    window.location.replace('/admin/login');
  };

  return (
    <nav className="sidebar">
      <div className="p-3 border-bottom">
        <div className="fw-bold" style={{ fontSize: '0.95rem', color: '#111827' }}>Knowledge Hub</div>
        <div className="text-muted" style={{ fontSize: '0.72rem' }}>Admin Portal</div>
      </div>

      {user && (
        <div className="d-flex align-items-center gap-2 p-3 border-bottom bg-light">
          <div className="user-avatar">{user.name?.charAt(0).toUpperCase()}</div>
          <div className="overflow-hidden">
            <div className="fw-semibold text-truncate" style={{ fontSize: '0.82rem', color: '#111827' }}>{user.name}</div>
            <div className="text-muted" style={{ fontSize: '0.72rem' }}>{user.department}</div>
          </div>
        </div>
      )}

      <ul className="nav flex-column flex-grow-1 py-2">
        <li className="nav-item">
          <NavLink to="/dashboard" className={({ isActive }) => 'nav-link' + (isActive ? ' active' : '')}>
            Dashboard
          </NavLink>
        </li>
        <li className="nav-item">
          <NavLink to="/materials" className={({ isActive }) => 'nav-link' + (isActive ? ' active' : '')}>
            Study Materials
          </NavLink>
        </li>
        <li className="nav-item">
          <NavLink to="/question-papers" className={({ isActive }) => 'nav-link' + (isActive ? ' active' : '')}>
            Question Papers
          </NavLink>
        </li>
      </ul>

      <div className="p-3 border-top">
        <button className="btn btn-outline-danger btn-sm w-100" onClick={handleLogout}>Logout</button>
      </div>
    </nav>
  );
}

export default Sidebar;
